CREATE TABLE HTTP_REQUESTS (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    method TEXT NOT NULL,
    ep TEXT NOT NULL,
    headers TEXT
);

CREATE TABLE HEATING_TEMPERATURES (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    modification_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    temperature REAL NOT NULL
);

CREATE TABLE FEEDING_HOURS (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    modification_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    hours TEXT NOT NULL
);

CREATE TABLE TANKS_STATES (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    quantities TEXT NOT NULL
);

CREATE TABLE INACTIVITY_PERIODS (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    modification_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    period REAL NOT NULL
);

CREATE TABLE FEEDING_LIMITS (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    modification_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    limita REAL NOT NULL
);