CREATE TABLE HTTP_REQUESTS (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    method TEXT NOT NULL,
    ep TEXT NOT NULL,
    headers TEXT
);

CREATE TABLE HEATING_TEMPERATURES (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    modification_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    temperature REAL NOT NULL
);

CREATE TABLE FEEDING_HOURS (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    modification_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    hours TEXT NOT NULL
);

CREATE TABLE TANKS_STATES (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    quantities TEXT NOT NULL
);

CREATE TABLE INACTIVITY_PERIODS (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    modification_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    period REAL NOT NULL
);

CREATE TABLE FEEDING_LIMITS (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    modification_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    val REAL NOT NULL
);

CREATE TABLE PET_DETECTIONS (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    detection_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE DISPENSING_TIMES (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    dispensing_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    food_type INTEGER NOT NULL,
    quantity REAL NOT NULL
);

CREATE TABLE NOTIFICATIONS (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    notification_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    message_text TEXT NOT NULL 
);